blank_issues_enabled: false

contact_links:
  - name: ğŸ­ Tanya / Diskusi (ID)
    url: https://github.com/naruyaizumi/liora/discussions
    about: Gunakan forum diskusi kalau ingin bertanya, berbagi ide, atau ngobrol santai ğŸ¬
  - name: ğŸ­ Ask / Discuss (EN)
    url: https://github.com/naruyaizumi/liora/discussions
    about: Use discussions for questions, ideas, or casual talk ğŸ¬

pull_request_templates:
  - name: ğŸ­ Pull Request (Bahasa Indonesia)
    path: .github/PULL_REQUEST_TEMPLATE/pull-request-id.md
  - name: ğŸ­ Pull Request (English)
    path: .github/PULL_REQUEST_TEMPLATE/pull-request-en.md