name: ğŸœ njsscan Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * 0'

permissions:
  contents: read

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: ğŸ£ njsscan Code Scanning
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: ğŸ™ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ¤ Run njsscan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: >
            . --sarif --output results.sarif

      - name: ğŸ° Upload njsscan report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
